sudo: false
language: python
env:
    - TOXENV=py27-dj1.9-dt1.1.0-tests
    - TOXENV=py27-dj1.9-dt1.1.1-tests
    - TOXENV=py27-dj1.9-dt1.1.2-tests
    - TOXENV=py27-dj1.9-dt1.1.4-tests
    - TOXENV=py27-dj1.9-dt1.1.7-tests
    - TOXENV=py27-dj1.9-dt1.1.8-tests
    - TOXENV=py27-dj1.9-dt1.2.0-tests
    - TOXENV=py27-dj1.9-dt1.2.1-tests
    - TOXENV=py27-dj1.9-dt1.2.2-tests
    - TOXENV=py27-dj1.9-dt1.2.3-tests
    - TOXENV=py27-dj1.9-dt1.2.6-tests
    - TOXENV=py34-dj1.9-dt1.1.0-tests
    - TOXENV=py34-dj1.9-dt1.1.1-tests
    - TOXENV=py34-dj1.9-dt1.1.2-tests
    - TOXENV=py34-dj1.9-dt1.1.4-tests
    - TOXENV=py34-dj1.9-dt1.1.7-tests
    - TOXENV=py34-dj1.9-dt1.1.8-tests
    - TOXENV=py34-dj1.9-dt1.2.0-tests
    - TOXENV=py34-dj1.9-dt1.2.1-tests
    - TOXENV=py34-dj1.9-dt1.2.2-tests
    - TOXENV=py34-dj1.9-dt1.2.3-tests
    - TOXENV=py34-dj1.9-dt1.2.6-tests
    - TOXENV=py27-dj1.10-dt1.1.0-tests
    - TOXENV=py27-dj1.10-dt1.1.1-tests
    - TOXENV=py27-dj1.10-dt1.1.2-tests
    - TOXENV=py27-dj1.10-dt1.1.4-tests
    - TOXENV=py27-dj1.10-dt1.1.7-tests
    - TOXENV=py27-dj1.10-dt1.1.8-tests
    - TOXENV=py27-dj1.10-dt1.2.0-tests
    - TOXENV=py27-dj1.10-dt1.2.1-tests
    - TOXENV=py27-dj1.10-dt1.2.2-tests
    - TOXENV=py27-dj1.10-dt1.2.3-tests
    - TOXENV=py27-dj1.10-dt1.2.6-tests
    - TOXENV=py34-dj1.10-dt1.1.0-tests
    - TOXENV=py34-dj1.10-dt1.1.1-tests
    - TOXENV=py34-dj1.10-dt1.1.2-tests
    - TOXENV=py34-dj1.10-dt1.1.4-tests
    - TOXENV=py34-dj1.10-dt1.1.7-tests
    - TOXENV=py34-dj1.10-dt1.1.8-tests
    - TOXENV=py34-dj1.10-dt1.2.0-tests
    - TOXENV=py34-dj1.10-dt1.2.1-tests
    - TOXENV=py34-dj1.10-dt1.2.2-tests
    - TOXENV=py34-dj1.10-dt1.2.3-tests
    - TOXENV=py34-dj1.10-dt1.2.6-tests
    - TOXENV=py27-flake
    - TOXENV=py34-flake

install:
  - pip install tox>=2.5.0
script:
  - tox

