sudo: false
language: python

matrix:
    include:
        - { python: 3.4, env: TOXENV=py34-djmaster-dt1.3-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.9-dtmaster-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.10-dtmaster-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.11-dtmaster-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.9-dtmaster-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.10-dtmaster-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.11-dtmaster-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.9-dt1.1-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.9-dt1.2-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.9-dt1.3-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.10-dt1.1-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.10-dt1.2-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.10-dt1.3-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.9-dt1.1-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.9-dt1.2-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.9-dt1.3-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.10-dt1.1-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.10-dt1.2-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.10-dt1.3-tests }
        - { python: 2.7, env: TOXENV=py27-dj1.11-dt1.3-tests }
        - { python: 3.4, env: TOXENV=py34-dj1.11-dt1.3-tests }
        - { python: 2.7, env: TOXENV=py27-flake }
        - { python: 3.4, env: TOXENV=py34-flake }
        - { python: 3.4, env: TOXENV=py34-isort }
    allow_failures:
        - env: TOXENV=py34-djmaster-dt1.3-tests
        - env: TOXENV=py27-dj1.9-dtmaster-tests
        - env: TOXENV=py27-dj1.10-dtmaster-tests
        - env: TOXENV=py27-dj1.11-dtmaster-tests
        - env: TOXENV=py34-dj1.9-dtmaster-tests
        - env: TOXENV=py34-dj1.10-dtmaster-tests
        - env: TOXENV=py34-dj1.11-dtmaster-tests

install:
    - pip install tox>=2.5.0
script:
    - tox
